global:
  git:
    repo: git@github.com:jralmaraz/forgeops-init.git
    branch: release/6.0.0
    sedFilter: "-e s/qa.mycompany.com/qa.mycompany.com/g"
  configPath:
    idm: default/idm/sync-with-ldap-bidirectional
  useTLS: false
  domain: .example.com
openidm:
  image:
    repository: hub.docker.com/jralmaraz/openidm
    tag: 6.0.0
opendj:
  image:
    repository: hub.docker.com/jralmaraz/opendj
    tag: 6.0.0

